basic loop of data being displayed, with some css
olivershooter/plog pull request #3
Opened 2023-04-27 18:43 UTC by Dave-Turnbull

forgot to make a new branch for the feature

2023-04-27 19:10 UTC, olivershooter requested changes

2023-04-27 19:10 UTC, olivershooter commented on src/App.js
> +// src/App.js
Top level comments should normally be large and clear:

`/*

  APP.JS

*/`

2023-04-27 19:10 UTC, olivershooter commented on src/App.js
> +import Litrature from "./litrature";
Literature or litrature?

2023-04-27 19:10 UTC, olivershooter commented on src/App.js
> +const dummyData = [
Would like to refactor this, logic should always go in seperate files and never top level in the app.js. We also probably just want to make a JSON file with this info and add it to the utils folder.

2023-04-27 19:10 UTC, olivershooter commented on src/App.js
> +        <Litrature
Nice use of components!

2023-04-27 19:10 UTC, olivershooter commented on src/index.css
> +  content: ""; /* Add this line to create the pseudo-element */
Don't mind some comments in here as its the CSS file, long as they're minimal (same for the JS files really, just need to keep it minimal as code should do the speaking)

2023-04-27 19:10 UTC, olivershooter commented on src/litrature.js
> +const Litrature = ({
Maybe not the right name for the file but for no doesn't matter. Normally name the thing they: "DummyData.js".

Also needs to go into a component folder. src/components/Literature/index.js

2023-04-27 19:11 UTC, olivershooter commented on src/App.js
> +// src/App.js
By top level I mean, comments that name the file to show what it is.

2023-04-28 09:03 UTC, Dave-Turnbull commented on src/App.js
> +// src/App.js
forgot to change this one

2023-04-28 09:03 UTC, Dave-Turnbull commented on src/App.js
> +import Litrature from "./litrature";
im bad at spelling

2023-04-28 09:03 UTC, Dave-Turnbull commented on src/App.js
> +const dummyData = [
i had to look up what refactor is, dummy data is in a json now

2023-04-28 09:03 UTC, Dave-Turnbull commented on src/App.js
> +        <Litrature
thanks chatGPT!

2023-04-28 09:04 UTC, Dave-Turnbull commented on src/litrature.js
> +const Litrature = ({
added to a component folder

2023-04-28 09:47 UTC, olivershooter submitted a review, later dismissed

2023-04-28 09:51 UTC, Dave-Turnbull commented
hello

2023-04-28 09:51 UTC, Dave-Turnbull reviewed
great work me!

2023-04-28 09:54 UTC, Dave-Turnbull reviewed
10/10 code

2023-04-28 09:54 UTC, Dave-Turnbull commented on src/App.js
> -  SRC/APP.JS
just testing commenting

2023-04-28 10:17 UTC, olivershooter approved these changes

2023-04-28 10:24 UTC, merged